name: Destroy Infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-oidc-role
        aws-region: us-east-1

    - name: Terraform Destroy
      run: terraform -chdir=infra/terraform destroy -auto-approve
