apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test
spec:
  restartPolicy: Never
  containers:
  - name: nvidia-test
    image: nvidia/cuda:13.0.1-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
